config/routes.rb
Rails.application.routes.draw do
  get 'places/index'

  root 'places#index'

  resources :places do
    get 'pickforme', on: :collection
  end

end

app/models/place.rb
class Place < ActiveRecord::Base
  validates :name, presence: true
  validates :location, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all
  end

  def new
    @place = Place.new
  end

  def show
    @place = Place.find(params[:id])
  end

  def edit
    @place = Place.find(params[:id])
  end

  def update
    @place = Place.find(params[:id])

    if @place.update(place_params)
      redirect_to @place
    else
      render 'edit'
    end
  end

  def create
    @place = Place.new(place_params)

    if @place.save
        redirect_to @place
      else
        render 'new'
      end
  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy

    redirect_to places_path
  end

  def pickforme
    flash[:picked] = Place.all.shuffle.first
    redirect_to root_url
  end

  private
    def place_params
      params.require(:place).permit(:name, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/places/_form.html.erb
<%= form_for @place do |f| %>

  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@place.errors.count, "error") %> prohibited
        this place from being saved:
      </h2>
      <ul>
        <% @place.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<% if flash[:picked] %>
  <h1>I've picked you this place!</h1>
  <%= flash[:picked]["name"] %> at <%= flash[:picked]["location"] %>
<% end %>

<h1>Listing Places</h1>
<%= link_to 'New place', new_place_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th colspan="3"></th>
  </tr>

  <% @places.each do |place| %>
    <tr>
      <td><%= place.name %></td>
      <td><%= place.location %></td>
      <td><%= link_to 'Show', place_path(place) %></td>
      <td><%= link_to 'Edit', edit_place_path(place) %></td>
      <td><%= link_to 'Destroy', place_path(place),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Pick For Me!", controller: "places", action: "pickforme" %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>
 
<p>
  <strong>Location:</strong>
  <%= @place.location %>
</p>
  
<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>